import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/Header";



export const metadata: Metadata = {
  title: "Tech Interpretations",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <div className="max-w-3xl mx-auto text-slate-800">
          <Header/>
          <main className="p-4 text-lg">
            {children}
          </main>
        </div>
       
      </body>
    </html>
  );
}
